export const pockerCards = {
  spade: [
    { rank: 'A', suit: 's' },
    { rank: '2', suit: 's' },
    { rank: '3', suit: 's' },
    { rank: '4', suit: 's' },
    { rank: '5', suit: 's' },
    { rank: '6', suit: 's' },
    { rank: '7', suit: 's' },
    { rank: '8', suit: 's' },
    { rank: '9', suit: 's' },
    { rank: '10', suit: 's' },
    { rank: 'J', suit: 's' },
    { rank: 'Q', suit: 's' },
    { rank: 'K', suit: 's' },
  ],

  heart: [
    { rank: 'A', suit: 'h' },
    { rank: '2', suit: 'h' },
    { rank: '3', suit: 'h' },
    { rank: '4', suit: 'h' },
    { rank: '5', suit: 'h' },
    { rank: '6', suit: 'h' },
    { rank: '7', suit: 'h' },
    { rank: '8', suit: 'h' },
    { rank: '9', suit: 'h' },
    { rank: '10', suit: 'h' },
    { rank: 'J', suit: 'h' },
    { rank: 'Q', suit: 'h' },
    { rank: 'K', suit: 'h' },
  ],

  diamond: [
    { rank: 'A', suit: 'd' },
    { rank: '2', suit: 'd' },
    { rank: '3', suit: 'd' },
    { rank: '4', suit: 'd' },
    { rank: '5', suit: 'd' },
    { rank: '6', suit: 'd' },
    { rank: '7', suit: 'd' },
    { rank: '8', suit: 'd' },
    { rank: '9', suit: 'd' },
    { rank: '10', suit: 'd' },
    { rank: 'J', suit: 'd' },
    { rank: 'Q', suit: 'd' },
    { rank: 'K', suit: 'd' },
  ],

  club: [
    { rank: 'A', suit: 'c' },
    { rank: '2', suit: 'c' },
    { rank: '3', suit: 'c' },
    { rank: '4', suit: 'c' },
    { rank: '5', suit: 'c' },
    { rank: '6', suit: 'c' },
    { rank: '7', suit: 'c' },
    { rank: '8', suit: 'c' },
    { rank: '9', suit: 'c' },
    { rank: '10', suit: 'c' },
    { rank: 'J', suit: 'c' },
    { rank: 'Q', suit: 'c' },
    { rank: 'K', suit: 'c' },
  ],
};
