const cards = [
  { id: '0', name: 'random1', shape: 'spade', num: 'A' },
  { id: '1', name: 'random2', shape: 'spade', num: '2' },
  { id: '2', name: 'random3', shape: 'spade', num: '3' },
  { id: '3', name: 'random4', shape: 'spade', num: '4' },
  { id: '4', name: 'random5', shape: 'spade', num: '5' },
  { id: '5', name: 'random6', shape: 'spade', num: '6' },
  { id: '6', name: 'random7', shape: 'spade', num: '7' },
  { id: '7', name: 'random8', shape: 'spade', num: '8' },
  { id: '8', name: 'random9', shape: 'spade', num: '9' },
  { id: '9', name: 'random10', shape: 'spade', num: '10' },
  { id: '10', name: 'random11', shape: 'spade', num: 'J' },
  { id: '11', name: 'random12', shape: 'spade', num: 'Q' },
  { id: '12', name: 'random13', shape: 'spade', num: 'K' },


  { id: '13', name: 'random14', shape: 'heart', num: 'A' },
  { id: '14', name: 'random15', shape: 'heart', num: '2' },
  { id: '15', name: 'random16', shape: 'heart', num: '3' },
  { id: '16', name: 'random17', shape: 'heart', num: '4' },
  { id: '17', name: 'random18', shape: 'heart', num: '5' },
  { id: '18', name: 'random19', shape: 'heart', num: '6' },
  { id: '19', name: 'random20', shape: 'heart', num: '7' },
  { id: '20', name: 'random21', shape: 'heart', num: '8' },
  { id: '21', name: 'random22', shape: 'heart', num: '9' },
  { id: '22', name: 'random23', shape: 'heart', num: '10' },
  { id: '23', name: 'random24', shape: 'heart', num: 'J' },
  { id: '24', name: 'random25', shape: 'heart', num: 'Q' },
  { id: '25', name: 'random26', shape: 'heart', num: 'K' },


  { id: '26', name: 'random27', shape: 'diamond', num: 'A' },
  { id: '27', name: 'random28', shape: 'diamond', num: '2' },
  { id: '28', name: 'random29', shape: 'diamond', num: '3' },
  { id: '29', name: 'random30', shape: 'diamond', num: '4' },
  { id: '30', name: 'random31', shape: 'diamond', num: '5' },
  { id: '31', name: 'random32', shape: 'diamond', num: '6' },
  { id: '32', name: 'random33', shape: 'diamond', num: '7' },
  { id: '33', name: 'random34', shape: 'diamond', num: '8' },
  { id: '34', name: 'random35', shape: 'diamond', num: '9' },
  { id: '35', name: 'random36', shape: 'diamond', num: '10' },
  { id: '36', name: 'random37', shape: 'diamond', num: 'J' },
  { id: '37', name: 'random38', shape: 'diamond', num: 'Q' },
  { id: '38', name: 'random39', shape: 'diamond', num: 'K' },


  { id: '39', name: 'random40', shape: 'club', num: 'A' },
  { id: '40', name: 'random41', shape: 'club', num: '2' },
  { id: '41', name: 'random42', shape: 'club', num: '3' },
  { id: '42', name: 'random43', shape: 'club', num: '4' },
  { id: '43', name: 'random44', shape: 'club', num: '5' },
  { id: '44', name: 'random45', shape: 'club', num: '6' },
  { id: '45', name: 'random46', shape: 'club', num: '7' },
  { id: '46', name: 'random47', shape: 'club', num: '8' },
  { id: '47', name: 'random48', shape: 'club', num: '9' },
  { id: '48', name: 'random49', shape: 'club', num: '10' },
  { id: '49', name: 'random50', shape: 'club', num: 'J' },
  { id: '50', name: 'random51', shape: 'club', num: 'Q' },
  { id: '51', name: 'random52', shape: 'club', num: 'K' },


  { id: '52', name: 'joker1', shape: 'joker', num: '1' },
  { id: '53', name: 'joker2', shape: 'joker', num: '2' }
];
